### ISSUE TITLE
permanent disconnect <> reconnect

### ISSUE THREAD

**Issue by mmd-app** [centrifugal/centrifuge-js#130]
permanent disconnect <> reconnect
what could be the problem? 

```
unsubscribe { channel: 'test' }
disconnected: connection closed true
Status connected -> disconnected
disconnect { reason: 'connection closed', reconnect: true }
reconnect after 1907 milliseconds
start connecting
Status disconnected -> connecting
reset retries count to 0
Status connecting -> connected
subscribing on test
no private channels found, no need to make request
```
```
config.yaml:
    v3_use_offset: true
    token_hmac_secret_key: xxx
    api_key: xxx
    admin_password: xxx
    admin_secret: xxx
    log_level: debug
    admin: true
    engine: memory
    websocket_compression: false
    client_anonymous: true
    client_insecure: true
    gomaxprocs: 1
    health: true
    debug: false
    sockjs_disable: true
    api_disable: false
    websocket_handler_prefix: /hub
```
ENV : GKE/k8s  image:  centrifugo/centrifugo:latest

**Comment by FZambia** [comment]
Hello @mmd-app, I can't really help based on this information. Please provide steps to reproduce.

**Comment by mmd-app** [comment]
> Hello @mmd-app, I can't really help based on this information. Please provide steps to reproduce.

Thanks for your quick response!

problem solved!
GKE default connection timeout 30 sec
increasing the timeout requires BackendConfig

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: centrifugo-backend
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800

```
