### ISSUE TITLE
Could not connect to centrifugo server using docker-compose

### ISSUE THREAD

**Issue by Mafioso** [centrifugal/centrifuge-js#5]
Hello, when I am running centrifugo in a docker container and my web app that serve client static content is running on the local host machine, connection to centrifugo server is well established. However, when I am trying to do the same, but using docker-compose by linking app with centrifugo, I receive connection error. Centrifugo Server receives http request, but it just logs it without any error code.

docker-compose.yml

```
app:
  image: anguis/natr_app:latest
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/natr
  ports:
    - "8000:8000"
  volumes_from:
    - media
  links:
    - centrifugo

centrifugo:
  image: fzambia/centrifugo:latest
  command: centrifugo -c config.json -w --port=8001  --log_level=debug --debug --insecure --address=0.0.0.0
  ports:
    - "8001:8001"
  volumes:
    - ./conf/centrifugo.json:/centrifugo/config.json   # centrifugo -c config.json -w /opt/centrifugo/web
```

Chrome console log

```
GET http://172.17.0.74:8001/connection/info?t=1448561808764 net::ERR_CONNECTION_REFUSED
```

Client connection setings
```
var centrifuge = new Centrifuge({
        url: '172.17.0.74:8001',
        user: '1',
        timestamp: '1448561553',
        token: '288aa3318b41a0f7b6fd547e2964ab7915f6f59d871e9b46f25c03ccffc15430'
      });
centrifuge.connect()
```
